name: Prometheus Slurm Exporter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  centos8:
    runs-on: ubuntu-latest
    container:
      image: centos:centos8

    steps:
      - uses: actions/checkout@v2
      - name: Install Prerequisites
        run: |
          dnf install -y rpm-build rpmdevtools redhat-rpm-config make git go
      - name: Configure Go Libraries
        run: |
          export GOPATH=$(pwd)
          rm -f go.mod
          go get -v -u github.com/prometheus/client_golang/prometheus
          go get -v -u github.com/sirupsen/logrus
          go get -v -u gopkg.in/alecthomas/kingpin.v2
          go get -v -u github.com/m3db/prometheus_common/log
          mkdir -p ${GOPATH}/src/github.com/prometheus/common/log/
          cp -r ${GOPATH}/src/github.com/m3db/prometheus_common/log/* ${GOPATH}/src/github.com/prometheus/common/log/
      - name: Compile Exporter
        run: make build
      - name: Prepare RPM Environment
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS,tmp}
          echo '%_topdir %(echo $HOME)/rpmbuild' > ~/.rpmmacros
          cp README.md ~/rpmbuild/SOURCES
          cp LICENSE ~/rpmbuild/SOURCES
          cp bin/prometheus-slurm-exporter ~/rpmbuild/SOURCES
          cp lib/systemd/prometheus-slurm-exporter.service ~/rpmbuild/SOURCES
          cp packages/rpm/*.spec ~/rpmbuild/SPECS
      - name: Build RPM
        run: |
          cd $HOME/rpmbuild
          spectool -g -R SPECS/prometheus-slurm-exporter.spec
          rpmbuild -ba SPECS/prometheus-slurm-exporter.spec
      - name: Upload RPM
        uses: actions/upload-artifact@v2
        with:
          name: prometheus-slurm-exporter-centos8-latest
          path: /github/home/rpmbuild/RPMS/x86_64/*.rpm
  centos7:
    runs-on: ubuntu-latest
    container:
      image: centos:centos7

    steps:
      - uses: actions/checkout@v2
      - name: Install Prerequisites
        run: |
          dnf install -y rpm-build rpmdevtools redhat-rpm-config make git go
      - name: Configure Go Libraries
        run: |
          export GOPATH=$(pwd)
          rm -f go.mod
          go get -v -u github.com/prometheus/client_golang/prometheus
          go get -v -u github.com/sirupsen/logrus
          go get -v -u gopkg.in/alecthomas/kingpin.v2
          go get -v -u github.com/m3db/prometheus_common/log
          mkdir -p ${GOPATH}/src/github.com/prometheus/common/log/
          cp -r ${GOPATH}/src/github.com/m3db/prometheus_common/log/* ${GOPATH}/src/github.com/prometheus/common/log/
      - name: Compile Exporter
        run: make build
      - name: Prepare RPM Environment
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS,tmp}
          echo '%_topdir %(echo $HOME)/rpmbuild' > ~/.rpmmacros
          cp README.md ~/rpmbuild/SOURCES
          cp LICENSE ~/rpmbuild/SOURCES
          cp bin/prometheus-slurm-exporter ~/rpmbuild/SOURCES
          cp lib/systemd/prometheus-slurm-exporter.service ~/rpmbuild/SOURCES
          cp packages/rpm/*.spec ~/rpmbuild/SPECS
      - name: Build RPM
        run: |
          cd $HOME/rpmbuild
          spectool -g -R SPECS/prometheus-slurm-exporter.spec
          rpmbuild -ba SPECS/prometheus-slurm-exporter.spec
      - name: Upload RPM
        uses: actions/upload-artifact@v2
        with:
          name: prometheus-slurm-exporter-centos7-latest
          path: /github/home/rpmbuild/RPMS/x86_64/*.rpm
